service: skyworkz
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  get:
    handler: bin/api/get
    events:
      - httpApi:
          path: /
          method: get
  post:
    handler: bin/api/post
    events:
      - httpApi:
          path: /
          method: post