name: go get build-lambda-zip 
on:
  push:
    branches: 
      - main

jobs:
  thejob:
    runs-on: ${{ matrix.platform }}
    name: install build-lambda-zip on ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [1.13]
        platform: [ubuntu-latest]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: go get
        env:
          GOPROXY: direct
          GO111MODULE: on
        run: |
          go env
          go get -u github.com/aws/aws-lambda-go/cmd/build-lambda-zip
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

